apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: yii2
spec:
  storageClassName: dblibripv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi