apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-libri-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wwwlibripv
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/k8smount
    server: 192.168.150.30